version: "3.9"

services:
  api:
    build: ./backend
    container_name: nasa2025_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://nasa2025:nasa2025_pw@db:5432/nasa2025
      GUNICORN_WORKERS: 4   # can adjust 
    depends_on:
      - db

  db:
    image: postgis/postgis:16-3.4
    container_name: nasa2025_db
    environment:
      POSTGRES_USER: nasa2025
      POSTGRES_PASSWORD: nasa2025_pw
      POSTGRES_DB: nasa2025
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  pgdata:
